# Generated by Django 4.2 on 2023-04-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Samachar',
        ),
    ]
